<a href="https://colab.research.google.com/github/YevheniiaMalchenko/ML/blob/main/%D0%9B%D0%911_%D0%9C%D0%B0%D0%BB%D1%8C%D1%87%D0%B5%D0%BD%D0%BA%D0%BE_3_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy
Студентки ФІТ 3-10 Мальченко Євгенії


**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
import numpy as np
np.__version__

'2.1.3'

## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [2]:
arr = np.array([2, 4, 6, 8, 101])
print(arr)
print(type(arr))

[  2   4   6   8 101]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [3]:
arr1 = np.zeros(10)
arr2 = np.ones(8)
arr3 = np.full(6,7)
print(arr1)

print(arr2)

print(arr3)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [4]:
arr = np. arange(1, 21)
even_arr = np. arange (2, 21, 2)
print(arr)
print(even_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [5]:
arr = np. linspace(0, 1, 11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [6]:
arr = np. arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [7]:
print("ndim: ", np.ndim(matrix))
print("shape:",np.shape(matrix))
print("size:", np.size(matrix))
print("dtype:", matrix.dtype)

ndim:  2
shape: (3, 4)
size: 12
dtype: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [8]:
arr = np.array ([1.2, 3.5, 5.7, 7.9])
int_arr = arr.astype(int)
print(arr)
print(int_arr)

[1.2 3.5 5.7 7.9]
[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print ("Перший елемент:", arr[0])
print ("oстанній елемент:", arr[-1])
print ("елементи з індексами від 2 до 5 включно",arr[2:6])
print ("кожен другий елемент:", arr[::2])


Перший елемент: 10
oстанній елемент: 80
елементи з індексами від 2 до 5 включно [30 40 50 60]
кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [10]:
matrix = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]])
print(matrix[1, 2])
print(matrix[1])
print(matrix[:, 2])
print("підматриця:")
print(matrix[1:, :2])

7
[5 6 7 8]
[ 3  7 11]
підматриця:
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [11]:
arr = np. arange(1, 16)
arr[5:10] = 0
print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

In [13]:
a+b

array([11, 22, 33, 44, 55])

In [14]:
a-b

array([ -9, -18, -27, -36, -45])

In [15]:
a*b

array([ 10,  40,  90, 160, 250])

In [16]:
a/b

array([0.1, 0.1, 0.1, 0.1, 0.1])

### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [17]:
arr = np.array([4, 8, 15, 16, 23, 42])

In [18]:
np.sum(arr)

np.int64(108)

In [19]:
np.mean(arr)

np.float64(18.0)

In [20]:
np.min(arr)

np.int64(4)

In [21]:
np.max(arr)

np.int64(42)

In [22]:
np.median(arr)

np.float64(15.5)

In [23]:
np.std(arr)

np.float64(12.315302134607444)

### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [24]:
matrix = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])


In [25]:
np.sum(matrix)


np.int64(45)

In [26]:
np.sum(matrix, axis=0)


array([12, 15, 18])

In [27]:
np. sum(matrix, axis=1)


array([ 6, 15, 24])

In [28]:
np.mean(matrix, axis =0)

array([4., 5., 6.])

### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [29]:
arr = np. arange(1, 11)


In [30]:
np.square(arr)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [33]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [36]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [37]:
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])



In [38]:
arr[arr>15]

array([18, 21, 25, 30, 34])

In [39]:
arr[arr % 2 == 0]

array([12, 18, 30, 34])

In [40]:
arr[(arr >=10) & (arr <= 30)]

array([12, 18, 21, 25, 30])

### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [41]:
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
print(arr)

[-5  3 -2  8 -1 10  0]


In [42]:
arr[arr < 0] = 0
print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [43]:
arr = np. random. randint(0, 101, size=20)
print (arr)


[49 88 62 58 41 72  8 67  1 66 61  4 22 77 70 46 58 35 25 23]


In [44]:
np.sum(arr > 50)

np.int64(10)

In [45]:
np.sum(arr <= 50)

np.int64(10)

## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [46]:
arr = np.arange(1,25)

In [47]:
arr.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [49]:
arr.reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [50]:
A = np.array([
    [1, 2],
     [3, 4]])

B = np.array([
    [5, 6],
     [7, 8]])


In [51]:
np.vstack((A, B))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
np.hstack((A, B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [53]:
matrix = np.arange(1, 13).reshape (3, 4)
flat_1 = matrix.flatten()
flat_2 = matrix.ravel()
print(flat_1)
print(flat_2)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [54]:
np.array_equal(flat_1,flat_2)

True

## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [55]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

In [56]:
a+b

array([ 3,  7, 11])

In [57]:
a-b

array([1, 1, 1])

In [58]:
a*3


array([ 6, 12, 18])

In [59]:
b*3

array([ 3,  9, 15])

### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [60]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [61]:
np.dot(a,b)

np.int64(32)

In [62]:
a@b

np.int64(32)

### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [63]:
v = np.array([3, 4])

In [64]:
norm = np.linalg.norm(v)
print(norm)

5.0


In [65]:
v/norm

array([0.6, 0.8])

### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [66]:
a = [1, 0, 0]
b = [0, 1, 0]

In [67]:
np.cross(a, b)

array([0, 0, 1])

### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [68]:
a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle_degrees = np.degrees(np.arccos(cos_angle))
print(angle_degrees)
print(cos_angle)


36.86989764584404
0.7999999999999998


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [69]:
A = np.array([
[1, 2, 31],
[4, 5, 6]])



In [70]:
A.T

array([[ 1,  4],
       [ 2,  5],
       [31,  6]])

In [71]:
np.transpose(A)

array([[ 1,  4],
       [ 2,  5],
       [31,  6]])

### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [72]:
A = np.array([[1, 2],
     [3, 4]])

B = np.array([[2, 0],
     [1, 2]])

In [73]:
A*B

array([[2, 0],
       [3, 8]])

In [74]:
A@B

array([[ 4,  4],
       [10,  8]])

### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [75]:
A = np.array([[4, 7],
     [2, 6]])

In [76]:
np.linalg.det(A)

np.float64(10.000000000000002)

In [77]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [78]:
A*Ainv

array([[ 2.4, -4.9],
       [-0.4,  2.4]])

### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [79]:
A = np.array([[2, 1],
     [1, 3]])
b = np.array([5, 6])

In [80]:
np.linalg.solve(A, b)

array([1.8, 1.4])

### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [81]:
I = np.eye(4)
A = np.arange(1, 17).reshape(4, 4)

In [82]:
I@A

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [83]:
A = np.array([
    [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

In [84]:
A+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [85]:
# Код студента
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([10, 20, 30])

In [86]:
A+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

NumPy автоматично дублює вектор v вздовж рядків матриці A, додаючи значення до кожного відповідного стовпця всіх рядків завдяки сумісності їхніх останніх вимірів.

### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [88]:
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]], dtype=float)

mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)

In [89]:
(A - mu) / sigma


array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [100]:
# Код студента
np.random.seed(42)

In [101]:
np.random.randint(1, 101, size=10)

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [102]:
np.random.rand(3, 3)

array([[0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264],
       [0.21233911, 0.18182497, 0.18340451]])

In [105]:
normal_values = np.random.randn(1000)
print(normal_values)

[ 2.07526087e+00 -6.89187818e-01  1.73596380e+00  1.97910783e-01
 -6.51418004e-01 -4.83885834e-01 -3.20347308e-01  4.24165946e-01
  5.22835488e-01 -5.73700004e-01 -2.43545923e-02  2.14227036e+00
  1.72754317e+00  4.36323670e-01  3.80034782e-02  1.20031327e-01
  6.13517973e-01 -1.02279257e+00 -2.57376537e-01 -1.66858407e+00
  3.99223123e-01  6.47195940e-01 -4.83186462e-01  1.57398676e+00
 -1.22576566e+00 -1.46437488e+00  2.24451819e-01  1.04709830e+00
  1.68392769e+00 -4.58884263e-01  1.07868083e+00 -3.85084695e-02
 -1.72627300e-01  8.83659937e-01  6.52322878e-01 -1.57639216e+00
  1.47654035e+00  1.38009135e+00 -6.25562702e-01  3.95803533e-01
  4.94030186e-01  2.60673766e-01 -5.50305154e-01 -6.71623368e-01
 -2.55540710e-02  1.17272902e+00  5.43600155e-01 -3.70614332e-01
  7.71698711e-01 -2.84854262e+00  1.14876570e+00 -1.73971378e+00
 -3.62440941e-01 -1.11966989e+00 -1.29468148e+00  1.16082679e+00
 -4.67701201e-01  3.46503882e-01 -4.69205789e-02  4.77040827e-01
  7.68218911e-02 -1.28299

In [107]:
mean_normal = np.mean(normal_values)
std_normal = np.std(normal_values)
print("Середнє:", mean_normal)
print("Стандартне відхилення:", std_normal)

Середнє: 0.059258418294120076
Стандартне відхилення: 0.9985787911322401


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [90]:
grades = np.random.randint(0, 101, size=30)


In [91]:
np.mean(grades)

np.float64(58.03333333333333)

In [92]:
np.max(grades)

np.int64(94)

In [93]:
np.min(grades)

np.int64(3)

In [94]:
np.sum(grades >= 60)

np.int64(16)

In [95]:
np.mean(grades >= 90) * 100

np.float64(26.666666666666668)

## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [108]:
# Код студента
sales = np.array([[120, 150, 170, 160],
                  [80,  90,  100, 110],
                  [200, 180, 210, 230]])

In [118]:
a = np.sum(sales, axis=1)
print(a)

[600 380 820]


In [121]:
b = np.sum(sales, axis=0)
print(b)

[400 420 480 500]


In [122]:
np.argmax(a)

np.int64(2)

In [123]:
np.argmax(b)

np.int64(3)

In [124]:
np.mean(sales, axis=1)

array([150.,  95., 205.])

### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [127]:
# Код студента
np.random.seed(42)
matrix = np.random.randint(1, 21, size=(5, 5))
print(matrix)

[[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]


In [128]:
np.trace(matrix)

np.int64(59)

In [129]:
np.trace(np.fliplr(matrix))

np.int64(32)

In [130]:
np.max(matrix, axis=1)

array([20, 19, 12, 17, 19])

In [131]:
np.min(matrix, axis=0)

array([ 2,  1,  2, 11,  4])

In [132]:
mean_val = np.mean(matrix)
print(mean_val)

10.52


In [133]:
modified_matrix = np.where(matrix < mean_val, 0, matrix)
print(modified_matrix)

[[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [134]:
# Код студента
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])

In [135]:
np.linalg.norm(A[0] - A[1])

np.float64(1.7320508075688772)

In [136]:
np.linalg.norm(A[0] - A[2])

np.float64(5.196152422706632)

In [137]:
np.linalg.norm(A[1] - A[2])

np.float64(6.928203230275509)

### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [140]:
# Код студента
np.random.seed(42)
matrix = np.random.randint(-10, 11, size=(4, 4))
print(matrix)

[[-4  9  4  0]
 [-3 10 -4  8]
 [ 0  0 10 -7]
 [-3 -8 10 -9]]


In [143]:
row_norms = np.linalg.norm(matrix, axis=1, keepdims=True)
print("Норми кожного рядка:", row_norms)

Норми кожного рядка: [[10.63014581]
 [13.74772708]
 [12.20655562]
 [15.93737745]]


In [145]:
normalized = matrix / row_norms
print(normalized)

[[-0.37628835  0.84664878  0.37628835  0.        ]
 [-0.21821789  0.72739297 -0.29095719  0.58191437]
 [ 0.          0.          0.81923192 -0.57346234]
 [-0.18823674 -0.50196464  0.62745581 -0.56471022]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [146]:
# Код студента
A = np.array([[1,  2,  1],
              [2,  1, -1],
              [3, -1,  2]])

In [147]:
b = np.array([9, 8, 3])

In [149]:
solution_x = np.linalg.solve(A, b)
print(solution_x)

[ 2.22222222  3.44444444 -0.11111111]


In [150]:
calculated_b = A @ solution_x
print(calculated_b)

[9. 8. 3.]


In [151]:
is_equal = np.allclose(calculated_b, b)
print(is_equal)

True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
